version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}testreactapi
    build:
      context: .
      dockerfile: testReactApi/Dockerfile

  client:
     image: client
     build: 
       context: ./test-react
       dockerfile: Dockerfile

  proxy: 
    image: nginx:mainline
